using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class TaxOffice : MonoBehaviour
{
    public int level = 1; // Default level of the tax office
    public int baseMoneyRate = 1; // Base money rate per second
    public GameManager gameManager; // Reference to the GameManager script
    public int currentMoneyRate; // Current money rate generated by the tax office
    public int initialUpgradeCost = 10; // Initial upgrade cost
    public int upgradeCostMultiplier = 5; // Multiplier for increasing upgrade cost
    public TMP_Text upgradeCostText;

    // Start is called before the first frame update
    void Start()
    {
        // Set the initial money rate based on the tax office level
        CalculateMoneyRate();

        // Update upgrade cost text
        UpdateUpgradeCostText();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    // Method to calculate the money rate based on the tax office level
    void CalculateMoneyRate()
    {
        currentMoneyRate = baseMoneyRate * level;
        gameManager.ratePerSecond += currentMoneyRate; // Add the current money rate to the GameManager
    }

    // Method to increase the tax office level
    public void IncreaseLevel()
    {
        if (gameManager.money >= CalculateUpgradeCost())
        {
            level++;
            gameManager.money -= CalculateUpgradeCost(); // Deduct upgrade cost from the player's money
            CalculateMoneyRate(); // Recalculate the money rate after upgrading
            UpdateUpgradeCostText(); // Update upgrade cost text
        }
        else
        {
            Debug.Log("Insufficient funds to upgrade the tax office!");
        }
    }

    // Method to calculate the cost of upgrading the tax office
    int CalculateUpgradeCost()
    {
        int upgradeCost = initialUpgradeCost * (int)Mathf.Pow(upgradeCostMultiplier, level - 2);
        return upgradeCost;

    }

    // Method to update the upgrade cost text on screen
    void UpdateUpgradeCostText()
    {
        if (upgradeCostText != null)
        {
            int upgradeCost = CalculateUpgradeCost();
            upgradeCostText.text = "Upgrade Tax Office for $" + upgradeCost.ToString();
        }
    }
}
